config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    member do
      delete :delete_attachment
    end
  end
  resources :stories

  # get 'home/index'
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many_attached :images
  belongs_to :user
  validate :max_images

  private

  def max_images
    if images.length > 10
      images_to_purge = images.drop(10)
      images_to_purge.each { |img| img.purge }
      errors.add(:images, "can't be more than 10")
    end
  end
end

app/models/story.rb
class Story < ApplicationRecord
  has_one_attached :image
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts
         has_many :stories

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    # @post = Post.new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    # @post = Post.new(post_params)
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.images.each { |i| i.purge }
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def delete_attachment
    @post = Post.find(params[:id])
    @post.images.find(params[:image_id]).purge
    redirect_to edit_post_path(@post)
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to posts_path, notice: "Not Authorized To Edit This Post" if @post.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:description, :user_id, images: [])
    end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: %i[ show destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:destroy]

  # GET /stories
  def index
    @stories = Story.all
  end

  # GET /stories/1
  def show
  end

  # GET /stories/new
  def new
    # @story = Story.new
    @story = current_user.stories.build
  end

  # POST /stories
  def create
    # @story = Story.new(story_params)
    @story = current_user.stories.build(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to story_url(@story), notice: "Story was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  def destroy
    if @story.image.attached?
      @story.image.purge
    end
    @story.destroy

    respond_to do |format|
      format.html { redirect_to stories_url, notice: "Story was successfully destroyed." }
    end
  end

  def correct_user
    @story = current_user.stories.find_by(id: params[:id])
    redirect_to stories_path, notice: "Not Authorized To Edit This Story" if @story.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def story_params
      params.require(:story).permit(:line, :image, :user_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg py-3" data-bs-theme="dark" style="background-color:#cd486b">
  <div class="container-fluid">
    <%= link_to 'Instagram Clone App', root_path, class:"navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About', home_about_path, class:"nav-link" %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Posts', posts_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Stories', stories_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>

      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-light" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>
<br/>
<p>Hello, World!</p>
<p>My name is Hassan Mahmood and this is my first Rails Web Application.</p>

app/views/home/index.html.erb
<h1>Hello, World!</h1>
<p>This is my Home page..</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>InstagramClone</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header' %>
    <br/>

    <% if notice %>
        <%= render 'layouts/alerts' %>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image %>

    <% if @post.images.attached? %>
      <% @post.images.each do |image| %>
        <% if image.id %>
          <div style="width:400px; height:auto">
            <%= image_tag image, style:"width:100%" %>
          </div>
          <%= link_to "Delete", post_path(@post) + "/delete_attachment?image_id=#{image.id}", method: :delete, class:"btn btn-danger" %>
        <% end %>
      <% end %>
    <% end %>
    <br/>

    <%= form.file_field :images, multiple: true %>
  </div>

  <div class="field mb-3">
    <%= form.number_field :user_id, id: :post_user_id, value:current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% if user_signed_in? %>

  <h1>Posts</h1>

  <%= link_to "Create Post", new_post_path, class:"btn btn-primary" %>
  <br/>

  <% @posts.reverse_each do |post| %>
    <% if post.user == current_user %>
      <br/>
      <div class="card">
        <div class="card-header">
          <p>Post created <%= distance_of_time_in_words(post.created_at, Time.now) %> ago</p>
        </div>
        <div class="card-body">
          <blockquote class="blockquote mb-0">
            <p><%= post.description %></p>

            <div class="row">
                <% post.images.each do |im| %>
                  <div class="col-sm-3 my-2">
                    <%= image_tag(im, style:"width:100%") %>
                  </div>
                <% end %>
            </div>

            <br/>
            <footer class="blockquote-footer">

              <cite>
              <%= link_to 'Show', post, class:"btn btn-secondary" %>
              <%= link_to 'Edit', edit_post_path(post), class:"btn btn-secondary" %>
              <%= link_to 'Delete', post, class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
              </cite>

            </footer>
          </blockquote>
        </div>
      </div>
    <% end %>
  <% end %>

<% else %>
  <h1>Hello, World!</h1>
  <p>You're not signed in..</p>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<div style="width:400px;height:auto">
  <% @post.images.each do |im| %>
    <%= image_tag(im, style:"width:100%") %>
    <br/><br/>
  <% end %>
</div>

<p>
  <p>Post created <%= distance_of_time_in_words(@post.created_at, Time.now) %> ago</p>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/stories/_form.html.erb
<%= form_with(model: story, local: true) do |form| %>
  <% if story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Text %>
    <%= form.text_area :line %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field mb-3">
    <%= form.number_field :user_id, id: :story_user_id, value:current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stories/index.html.erb
<% if user_signed_in? %>

  <h1>Stories</h1>

  <%= link_to "Create Story", new_story_path, class:"btn btn-primary" %>
  <br/>

  <% @stories.reverse_each do |story| %>
    <% if story.user == current_user %>
      <br/>
      <div class="card">
        <div class="card-header">
          <p>Story created <%= distance_of_time_in_words(story.created_at, Time.now) %> ago</p>
        </div>
        <div class="card-body">
          <blockquote class="blockquote mb-0">
            <p><%= story.line %></p>


            <% if story.image.attached? %>
              <div style="width:400px;height:auto">
                <%= image_tag(story.image, style:"width:100%") %>
              </div>
            <% end %>

            <br/>
            <footer class="blockquote-footer">

              <%= link_to 'Show', story, class:"btn btn-secondary" %>
              <%= link_to 'Delete', story, class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>

            </footer>
          </blockquote>
        </div>
      </div>
    <% end %>
  <% end %>

<% else %>
  <h1>Hello, World!</h1>
  <p>You're not signed in..</p>
<% end %>

app/views/stories/new.html.erb
<h1>New Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p>
  <strong><%= @story.line %></strong>
</p>

<div style="width:400px;height:auto">
  <% if @story.image.attached? %>
    <%= image_tag(@story.image, style:"width:100%") %>
    <br/>
  <% end %>
</div>
<p>
  <p>Story created <%= distance_of_time_in_words(@story.created_at, Time.now) %> ago</p>
</p>

<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>